import { fileURLToPath } from 'url';
import path from 'path';

import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import alias from '@rollup/plugin-alias';
import copy from 'rollup-plugin-copy';
import { obsidianExportPath } from './env.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const isProd = process.env.BUILD === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP

If you want to view the source code, visit:
https://github.com/himanshu-17lodhi/SlashFlow
*/
`;

const cmModules = [
  '@codemirror/autocomplete',
  '@codemirror/closebrackets',
  '@codemirror/collab',
  '@codemirror/comment',
  '@codemirror/commands',
  '@codemirror/fold',
  '@codemirror/highlight',
  '@codemirror/gutter',
  '@codemirror/history',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/matchbrackets',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/stream-parser',
  '@codemirror/rangeset',
  '@codemirror/panel',
  '@codemirror/matchbrackets',
  '@codemirror/text',
  '@codemirror/tooltip',
  '@codemirror/view',
];

export default {
  input: './src/main.ts',
  output: {
    file: './dist/main.js',
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian', ...cmModules],
  plugins: [
    alias({
      entries: [
        {
          find: '@',
          replacement: path.resolve(__dirname, 'src'),
        },
      ],
    }),
    typescript({
      tsconfig: './tsconfig.lib.json',
    }),
    nodeResolve({ browser: true }),
    commonjs(),
    copy({
      targets: [
        { src: './main.js', dest: obsidianExportPath },
        { src: './manifest.json', dest: obsidianExportPath },
        { src: './src/styles.css', dest: obsidianExportPath },
      ],
      hook: 'writeBundle',
    }),
  ],
  onwarn: (warning) => {
    if (warning.code === 'THIS_IS_UNDEFINED') return;

    console.warn(warning.message);
  },
};
